### ISSUE TITLE
Snap/flatpak/appimage

### ISSUE THREAD

**Issue by rdscorreia74** [wastis/MediaPlayerRemoteInterface#1]
Hi there.
Not saying I'm going to dive in on using MPRIS if you do but, would you please consider creating a snap package for it? Or maybe even a flatpak or appimage package.
Otherwise only debian based distros will have access to it.
Thanks in advance.
Cheers

**Comment by wastis** [comment]
Thanks for the comment. Provided Team-Kodi will accept it, the addon will be included into Kodi's standard repository and thus available on any linux based installation from within Kodi where Kodi is available. There is no need for any installation on OS side.

[playerctl](https://github.com/altdesktop/playerctl) used in the testing scenario is out of my control.
